apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      nodeSelector:
        node-instance-type: db-optimized
      tolerations:
        - key: db-node
          operator: Exists
          effect: NoSchedule
      containers:
        - name: mysql
          # mysql:8
          image: mysql@sha256:713a3c26c5130f06fe17b16b314f1058f9efeb07330164da0e81d97d5a57d50b
          securityContext:
            runAsUser: 1000
            allowPrivilegeEscalation: false
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbpass
                  key: dbpass
          ports:
            - containerPort: 3306
              name: mysql
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 20
            periodSeconds: 10
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /data
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: efs-claim
