apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-service
  labels:
    app: stats-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stats-service
  template:
    metadata:
      labels:
        app: stats-service
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - stats-service
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: stats-service
          image: cloud.canister.io:5000/akibrat95/stats-service:latest
          ports:
            - containerPort: 8083
          livenessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8083
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8083
            initialDelaySeconds: 20
            periodSeconds: 10
      imagePullSecrets:
        - name: canistercred
